Kubernetes intro
otus-kuber-2019-12/artsiomrudenia_platform pull request #1
Opened 2019-12-17 16:20 UTC by artsiomrudenia

Все pod в своем yaml-файле имеют restartPolicy: Always.
Различные pod управляются различными контроллерами (Deployment-контроллер, ReplicaSet-контроллер и т.д.).
Т.к. контроллер запрашивает у API состояние объектов, которые он контролирует, то после удаления он получает статус пода из API и триггерит Scheduler, который дает приказ kubelet развернуть под.

2019-12-18 16:43 UTC, artsiomrudenia commented
Добрый вечер! А можно узнать, что сейчас не так?

2019-12-19 08:28 UTC, Avtandilko requested changes

2019-12-19 08:28 UTC, Avtandilko commented on kubernetes-intro/web-pod.yaml
> +    command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platformsnippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
Привет. Вот тут ссылка такой должна быть. https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh

У вас https://raw.githubusercontent.com/express42/otus-platformsnippets/master/Module-02/Introduction-to-Kubernetes/wget.sh, потерялся дефис

2019-12-19 08:55 UTC, artsiomrudenia commented on kubernetes-intro/web-pod.yaml
> +    command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platformsnippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
Привет. добавил дефис. Запустил тесты еще раз, но ошибка та же. Нудно создавать новый pull request или уже проблема в другом?

2019-12-19 15:13 UTC, Avtandilko commented on kubernetes-intro/web-pod.yaml
> +    command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platformsnippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
Насколько я вижу - еще, как минимум, проблема в том, что у вас контейнер слушает порт 8080, а тесты проверяют порт 8000

2019-12-20 11:20 UTC, artsiomrudenia commented on kubernetes-intro/web-pod.yaml
> +    command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platformsnippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
Это исправил, 1 тест прошел. В output travis вижу, что он вернул nginx homepage. Я правильно понимаю, что второй тест не прошел из-за прав на homework.html?

2019-12-24 19:13 UTC, Avtandilko commented on kubernetes-intro/web-pod.yaml
> +    command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platformsnippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
Привет. Сори за долгий ответ.
Объясню логику теста.

При выполнении задания вы через command скачиваете в init-container некий скрипт и кладете его содержимое в index.html (который через volume шарится с основным контейнером). Потом тест проверяет, что отдается именно содержимое этого скрипта (через зашитую строку для проверки). У вас сейчас отидается стартовая страница nginx вместо файла index.html.

Сам манифест вроде написан корректно, так что проблема, вероятно в контейнере с nginx (не увидел, что он из /app пытается читать какие-то файлы).

2019-12-24 19:14 UTC, Avtandilko commented on kubernetes-intro/web-pod.yaml
> +    command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platformsnippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
Даже нашел хак, из-за которого не работает:
COPY ./app /usr/share/nginx/html инструкция в dockerfile, а файл в директорию /app попадает в уже готовый и собранный контейнер :)

2019-12-25 15:59 UTC, artsiomrudenia commented on kubernetes-intro/web-pod.yaml
> +    command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platformsnippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
Спасибо! Попробую попозже с nginx еще попробовать. 
Пока с простым веб-сервером тест как я понимаю прошел.

2019-12-25 16:17 UTC, artsiomrudenia commented on kubernetes-intro/web-pod.yaml
> +    command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platformsnippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
А что происходит в Test CI - Branch? Это ведь тест web.yaml?

2019-12-25 21:14 UTC, Avtandilko commented on kubernetes-intro/web-pod.yaml
> +    command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platformsnippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
Мне кажется - проще в slack перейти, там быстрее сообщения будут доходить :) Про Test CI - Branch не очень понял вопрос, чем Test CI - Branch от Travis CI - Pull Request  отличается, или какие именно проверки там выполняются?

2019-12-25 21:46 UTC, merged

2019-12-25 22:01 UTC, artsiomrudenia commented on kubernetes-intro/web-pod.yaml
> +    command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platformsnippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
Странно, сейчас зашел и все тесты прошли - сделал merge и в кабинете увидел, что ДЗ принята. Значит вопросов нет, можно делать вторую. Спасибо за помощь!